config/routes.rb
BadPhotoWebsite::Application.routes.draw do
  root 'static_pages#home'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/la', to: 'static_pages#la', via: 'get'
  match '/modelTests', to: 'static_pages#modelTests', via: 'get'
  match '/nyc', to: 'static_pages#nyc', via: 'get'
  match '/ohio', to: 'static_pages#ohio', via: 'get'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def la
  end

  def modelTests
  end

  def nyc
  end

  def ohio
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# Get full title for site
	def full_title(page_title)
		base_title = "BADPHOTO"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_copyright.html.erb
<div class="copyright">
	<p>All photographs that appear on this website are the sole copyright of Brett Davis and are protected under the Copyright Laws of the United States.<br/>Reproduction, storage or transmission of any images by any means is prohibited without the express prior written permission of Brett Davis.</p>
</div>

app/views/layouts/_footer.html.erb
<footer>
	<div class="container">
		<small>
			Developed by: Matt Hinger
		</small>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
		<div class="container">
			<div class="navbar-header">
				<nav>
					<%= link_to "BADPHOTO", root_path, id: "logo" %>
					<ul class="nav pull-right">
						<li><%= link_to "About", about_path %></li>
						<li><%= link_to "Contact", contact_path %></li>
					</ul>
				</nav>
			</div>
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
<nav class="sidebar" >
	<ul class="pull-left">
		<li class="<%= "selected" if current_page?(modelTests_path) %>"><%= link_to "Model Tests", modelTests_path %></li>
		<li class="<%= "selected" if current_page?(la_path) %>"><%= link_to "LA", la_path %></li>
		<li class="<%= "selected" if current_page?(nyc_path) %>"><%= link_to "NYC", nyc_path %></li>
		<li class="<%= "selected" if current_page?(ohio_path) %>"><%= link_to "Ohio", ohio_path %></li>
	</ul>
<nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= full_title(yield(:title)) %></title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="robots" content="all" />
		<meta name="MSSmartTagsPreventParsing" content="true" />
		<meta name="description" content="Brett Davis Photography Portfolio" />
		<meta name="keywords" content="Brett Davis Photography Portfolio BADPHOTO" />
		<meta name="author" content="Matt Hinger" />
		<meta property="og:title" content="Brett Davis Photography"/>
		<meta property="og:site_name" content="BADPHOTO"/>
		<meta property="og:url" content="http://brettdavisphotography.tumblr.com/">
		<meta property="og:type" content="portfolio" />

		<%= favicon_link_tag '/favicon.ico' %>

		<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>

		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>

		<%= csrf_meta_tags %>
		<%= render 'layouts/shim' %>

	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<div class="row">
				<div class="span2">
					<%= render 'layouts/sidebar' %>
				</div>
				<div class="span10">
					<%= yield %>
				</div>
			</div>
		</div>
		<%= render 'layouts/footer' %>


		<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
	    <script src="https://code.jquery.com/jquery.js"></script>
	    <!-- Include all compiled plugins (below), or include individual files as needed -->
	    <!--script src="/assets/bootstrap.min.js"></script-->
	</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<div class="center hero-unit">
	<p>
		Photographer. Brooklyn, NY.<br/>
		In 2011 I was rejected by the Lakota East High School Craft Show.
	</p>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<div class="center hero-unit">
	<p>###-###-####</p>
	<p>badavisphoto@gmail.com</p>
</div>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
	<h1>BADPHOTO</h1>
	<div class="row">
		<div class="col-xs-6">
			<a href='/modelTests' class="thumbnail">
				<%= image_tag("modelTests/testShoot1.jpg", alt: "tests") %>
			</a>
		</div>
		<div class="col-xs-6">
			<a href='/la' class="thumbnail">
				<%= image_tag("la/la1.jpg", alt: "los angeles") %>
			</a>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-6">
			<a href='/nyc' class="thumbnail">
				<%= image_tag("nyc/nyc1.jpg", alt: "nyc") %>
			</a>
		</div>
		<div class="col-xs-6">
			<a href='/ohio' class="thumbnail">
				<%= image_tag("ohio/ohio1.jpg", alt: "oh") %>
			</a>
		</div>
	</div>
</div>

app/views/static_pages/la.html.erb
<% provide(:title, 'LA') %>
<div id="laCarousel" class="carousel" data-ride="carousel">
	<!-- indicators -->
	<ol class="carousel-indicators">
		<li data-target="#laCarousel" data-slide-to="0" class="active"></li>
		<li data-target="#laCarousel" data-slide-to="1"></li>
		<li data-target="#laCarousel" data-slide-to="2"></li>
    </ol>
	<div id="image-frame" class="carousel-inner">
		<div class="item active">
			<%= image_tag("la/la1.jpg", alt: "First image", id: "first") %>
		</div>
		<div class="item">
			<%= image_tag("la/la2.jpg", alt: "Second image") %>
		</div>
		<div class="item">
			<%= image_tag("la/la3.jpg", alt: "Third image") %>
		</div>
	</div>
	<a class="left carousel-control" href='' data-slide="prev">
		<span class="glyphicon glyphicon-chevron-left"></span>
	</a>
	<a class="right carousel-control" href='' data-slide="next">
		<span class="glyphicon glyphicon-chevron-right"></span>
	</a>
</div>
<div class="photo-caption">
	<small><p><b>September 2013</b> | Tags: LA, b&amp;w, 35mm, yashica t4, film, photography, neopan, LAX, palmtree</p></small>
</div>
<%= render 'layouts/copyright' %>

app/views/static_pages/modelTests.html.erb
<% provide(:title, 'Model Tests') %>
<div id="modelTestsCarousel" class="carousel" data-ride="carousel">
	<!-- indicators -->
	<ol class="carousel-indicators">
		<li data-target="#modelTestsCarousel" data-slide-to="0" class="active"></li>
		<li data-target="#modelTestsCarousel" data-slide-to="1"></li>
		<li data-target="#modelTestsCarousel" data-slide-to="2"></li>
    </ol>
	<div id="image-frame" class="carousel-inner">
		<div class="item active">
			<%= image_tag("modelTests/testShoot1.jpg", alt: "First image", id: "first") %>
		</div>
		<div class="item">
			<%= image_tag("modelTests/testShoot2.jpg", alt: "Second image") %>
		</div>
		<div class="item">
			<%= image_tag("modelTests/testShoot3.jpg", alt: "Third image") %>
		</div>
	</div>
	<a class="left carousel-control" href='' data-slide="prev">
		<span class="glyphicon glyphicon-chevron-left"></span>
	</a>
	<a class="right carousel-control" href='' data-slide="next">
		<span class="glyphicon glyphicon-chevron-right"></span>
	</a>
</div>
<%= render 'layouts/copyright' %>

app/views/static_pages/nyc.html.erb
<% provide(:title, 'NYC') %>
<div id="nycCarousel" class="carousel" data-ride="carousel">
	<!-- indicators -->
	<ol class="carousel-indicators">
		<li data-target="#nycCarousel" data-slide-to="0" class="active"></li>
		<li data-target="#nycCarousel" data-slide-to="1"></li>
		<li data-target="#nycCarousel" data-slide-to="2"></li>
    </ol>
	<div id="image-frame" class="carousel-inner">
		<div class="item active">
			<%= image_tag("nyc/nyc1.jpg", alt: "First image", id: "first") %>
		</div>
		<div class="item">
			<%= image_tag("nyc/nyc2.jpg", alt: "Second image") %>
		</div>
		<div class="item">
			<%= image_tag("nyc/nyc3.jpg", alt: "Third image") %>
		</div>
	</div>
	<a class="left carousel-control" href='' data-slide="prev">
		<span class="glyphicon glyphicon-chevron-left"></span>
	</a>
	<a class="right carousel-control" href='' data-slide="next">
		<span class="glyphicon glyphicon-chevron-right"></span>
	</a>
</div>
<%= render 'layouts/copyright' %>

app/views/static_pages/ohio.html.erb
<% provide(:title, 'Ohio') %>
<div id="ohioCarousel" class="carousel" data-ride="carousel">
	<!-- indicators -->
	<ol class="carousel-indicators">
		<li data-target="#ohioCarousel" data-slide-to="0" class="active"></li>
		<li data-target="#ohioCarousel" data-slide-to="1"></li>
		<li data-target="#ohioCarousel" data-slide-to="2"></li>
    </ol>
	<div id="image-frame" class="carousel-inner">
		<div class="item active">
			<%= image_tag("ohio/ohio1.jpg", alt: "First image", id: "first") %>
		</div>
		<div class="item">
			<%= image_tag("ohio/ohio2.jpg", alt: "Second image") %>
		</div>
		<div class="item">
			<%= image_tag("ohio/ohio3.jpg", alt: "Third image") %>
		</div>
	</div>
	<a class="left carousel-control" href='' data-slide="prev">
		<span class="glyphicon glyphicon-chevron-left"></span>
	</a>
	<a class="right carousel-control" href='' data-slide="next">
		<span class="glyphicon glyphicon-chevron-right"></span>
	</a>
</div>
<%= render 'layouts/copyright' %>